baseURL = "/wiki"
languageCode = "en-us"
title = "(PCC)^2 Wiki"
theme = "hugo-theme-learn"

[params]
editURL = "https://github.com/ArchWizard56/pcc-cybersecurity-club.github.io/tree/master/_wiki/content/"
themeVariant = "blue"
titleSeparator = "-"

[outputs]
home = [ "HTML", "RSS", "JSON"]
