name: Deploy site

on:
    push:
        branches:
        - master

jobs:
    deploy:
        runs-on: ubuntu-18.04
        steps:
        - name: Cloning repository  
          uses: actions/checkout@v2

        - name: Setting up gem cache
          uses: actions/cache@v2
          with:
            path: vendor/bundle
            key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
            restore-keys: |
              ${{ runner.os }}-gems-

        - name: Setup Hugo
          uses: peaceiris/actions-hugo@v2
          with:
            hugo-version: '0.68.3'

        - name: Setup ruby
          uses: actions/setup-ruby@v1
          with:
            ruby-version: '2.6'

        - name: Build site
          run: |
            sudo apt-get -yqq install libpq-dev
            gem install bundler
            bundle config path vendor/bundle
            bundle install --jobs 4 --retry 3
            bundle exec jekyll build

        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
            external_repository: archwizard56/pcc-cybersecurity-club.github.io 
            publish_dir: ./_site
